Siie/urls.py
from . import views
# from dajaxice.core.Dajaxice import dajaxice_autodiscover
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#
# dajaxice_autodiscover()


urlpatterns = patterns('',
                       # Examples:

                       url(r'^academica/', include('academica.urls')),
                       # url(r'^/accounts/login/$', include('allauth.urls', namespace='allauth', app_name='allauth')),
                       url(r'^$', 'Siie.views.login', name="login"),
                       url(r'^Index', login_required(views.Index.as_view()), name="Index"),
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^accounts/', include('allauth.urls')),
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^markdown/', include("django_markdown.urls")),
                       url(r'^', include('users.urls', namespace='users')),
                       url(r'^', include('reportes.urls', namespace='reportes')),
                       #url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls'))

                       )

if getattr(settings, "DEBUG", False):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academica/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required, permission_required


from academica.views import PlanCreate, \
    PlanUpdate, ExtracurricularesCreate, GrupoCreate, GruposList, HorarioCreate, HorarioList, MateriaCreate, \
    MateriaList, MaestroCreate, MaestroList, CalificacionCreate, AlumnoCreate, AlumnoUpdate, \
    GrupoUpdate, CarreraCreate, CarreraList, AlumnoList, CicloSemestralCreate, CicloSemestralList, PlanEstudioList, \
    BajaCreate, CicloSemestralUpdate, CarreraUpdate, EncuestaCreate, \
    EncuestaList, ReinscripcionList, Home, EstadoCreate, EstadoList, MunicipioList, \
    MunicipioCreate, AulaCreate, AulaList, CalificacionList, ExtracurricularList, ServicioSocialCreate, \
    ServicioSocialList, ServicioLiberadosList, BecaCreate, BecaList, TipoBecaCreate, TipoBecaList, EscuelaCreate, \
    EscuelaList, BibliotecaCreate, BibliotecaList, CentroComputoCreate, CentroComputoList, ContabilidadCreate, \
    ContabilidadList, BajaBiblioteca, BibliotecaUpdate, BajaCC, CCUpdate, BajaConta, ContaUpdate, CalificacionesUpdate, \
    ServicioUpdate, AlumnoReins, SemestreCreate, SemestreList, CalificacionesListByMateria

__author__ = 'Luisk'

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       # Examples:
                       url(r'^$', Home.as_view(), name='home'),
                       url(r'^deveploment/', TemplateView.as_view(template_name="404.html")),
                       # url(r'^list/$', AlumnosList.as_view(), name='alumnos-list'),
                       # planEstudio
                       url(r'planEstudio/add/$',permission_required('users.permissions_administrador', login_url='login')( PlanCreate.as_view()), name='planEstudio-add'),
                       url(r'planEstudio/(?P<pk>[0-9]+)/$',permission_required('users.permissions_administrador', login_url='login')(  PlanUpdate.as_view()), name='planEstudio-update'),
                       url(r'planEstudio/list/$', permission_required('users.permissions_administrador', login_url='login')( PlanEstudioList.as_view()), name='list-planEstudio'),
                       # Alumno
                       url(r'alumno/add/$',permission_required('users.permissions_administrador', login_url='login')(  AlumnoCreate.as_view()), name='alumno-add'),
                       url(r'alumno/(?P<pk>[0-9]+)/$', AlumnoUpdate.as_view(), name='alumno-update'),
                       url(r'alumnore/(?P<pk>[0-9]+)/$', AlumnoReins.as_view(), name='alumnore-update'),
                       url(r'alumno/list/$', AlumnoList.as_view(), name='list-alumno'),
                       url(r'^alumno/re/$', ReinscripcionList.as_view(), name='alumno-re'),
                       url(r'^alumno-ajax/$', ReinscripcionList.AlumnoAjax, name='alumno-ajax'),
                       url(r'^buscarexp-ajax/$', AlumnoCreate.buscar_exp_ajax, name='buscarexp-ajax'),
                       # Extracurriculares
                       url(r'alumno/add/addExtracurricular/$', ExtracurricularesCreate.as_view(), name='extra-add'),
                       url(r'^extracurricular/list$', ExtracurricularList.as_view(), name='list-extra'),
                       # grupos
                       url(r'grupo/add/$',permission_required('users.permissions_administrador', login_url='login')(  GrupoCreate.as_view()), name='grupo-add'),
                       url(r'grupo/list/$',permission_required('users.permissions_administrador', login_url='login')(  GruposList.as_view()), name='list-grupos'),
                       url(r'grupo/(?P<pk>[0-9]+)/$',permission_required('users.permissions_administrador', login_url='login')(  GrupoUpdate.as_view()), name='grupo-update'),
                       # horario
                       url(r'horario/add/$', HorarioCreate.as_view(), name='horario-add'),
                       url(r'horario/list/$', HorarioList.as_view(), name='list-horario'),
                       url(r'myhorario/$',permission_required('users.permissions_estudiante', login_url='login')(HorarioList.get_my_horarios), name='my-horarios'),
                       # materias
                       url(r'materia/add/$', MateriaCreate.as_view(), name='materia-add'),
                       url(r'materia/list/$', MateriaList.as_view(), name='list-materias'),
                       # maestros
                       url(r'maestro/add/$', MaestroCreate.as_view(), name='maestro-add'),
                       url(r'maestro/list/$', MaestroList.as_view(), name='list-maestro'),
                       # calificaciones
                       url(r'calificacion/add/$', CalificacionCreate.as_view(), name='calificacion-add'),
                       url(r'calificacion/list/$', CalificacionList.as_view(), name='list-calificacion'),
                       url(r'califAlum/(?P<alumno_id>\d+)/$', CalificacionList.get_calificacionesbyAlumno,
                           name='califi-alumno'),
                       url(r'myCalif/$',permission_required('users.permissions_estudiante', login_url='login')(  CalificacionList.get_my_calificaciones), name='my-califi'),
                       url(r'calificacion/update/(?P<pk>[0-9]+)/$', CalificacionesUpdate.as_view(), name='calificacion-update'),
                       # carrera
                       url(r'carrera/add/$', CarreraCreate.as_view(), name='carrera-add'),
                       url(r'carrera/list/$', CarreraList.as_view(), name='list-carrera'),
                       url(r'carrera/update/(?P<pk>[0-9]+)/$', CarreraUpdate.as_view(), name='carrera-update'),
                       # semestre
                       url(r'ciclosemestral/add/$',permission_required('users.permissions_administrador', login_url='login')(  CicloSemestralCreate.as_view()), name='semestre-add'),
                       url(r'ciclosemestral/list/$',permission_required('users.permissions_administrador', login_url='login')(  CicloSemestralList.as_view()), name='list-semestre'),
                       url(r'ciclosemestral/update/(?P<pk>[0-9]+)/$',permission_required('users.permissions_administrador', login_url='login')(  CicloSemestralUpdate.as_view()),
                           name='semestre-update'),
                       url(r'^semestre-ajax/$', CicloSemestralList.SemestreAjax, name='semestre-ajax'),

                       #buscar en el menu donde poner esto
                       url(r'semestre/add/$',permission_required('users.permissions_administrador', login_url='login')(SemestreCreate.as_view()), name='sem-add'),
                       url(r'semestre/list/$',permission_required('users.permissions_administrador', login_url='login')( SemestreList.as_view()), name='list-sem'),

                        url(r'^extracurricular-ajax/$', ExtracurricularList.ExtracurricularAjax, name='extracurricular-ajax'),

                       url(r'baja/$',permission_required('users.permissions_administrador', login_url='login')( BajaCreate.as_view()), name='baja-add'),

                       url(r'biblioteca/add$', BibliotecaCreate.as_view(), name='biblio-add'),
                       url(r'biblioteca/list$', BibliotecaList.as_view(), name='list-biblio'),
                       url(r'biblioteca/delete$', BajaBiblioteca.as_view(), name='baja-biblio'),
                       url(r'biblioteca/(?P<pk>[0-9]+)/$', BibliotecaUpdate.as_view(), name='biblio-update'),

                       url(r'centrocomp/add$', CentroComputoCreate.as_view(), name='cc-add'),
                       url(r'centrocomp/list$', CentroComputoList.as_view(), name='list-cc'),
                       url(r'centrocomp/delete$', BajaCC.as_view(), name='baja-cc'),
                       url(r'centrocomp/(?P<pk>[0-9]+)/$', CCUpdate.as_view(), name='cc-update'),

                       url(r'contabilidad/add$', ContabilidadCreate.as_view(), name='conta-add'),
                       url(r'contabilidad/list$', ContabilidadList.as_view(), name='list-conta'),
                       url(r'centrocomp/delete$', BajaConta.as_view(), name='baja-cont'),
                       url(r'centrocomp/(?P<pk>[0-9]+)/$', ContaUpdate.as_view(), name='cont-update'),

                       url(r'encuesta/add/$',permission_required('users.permissions_administrador', login_url='login')(  EncuestaCreate.as_view()), name='encuesta-add'),
                       url(r'encuesta/list/$',permission_required('users.permissions_administrador', login_url='login')(  EncuestaList.as_view()), name='list-encuesta'),

                       url(r'estado/add/$',permission_required('users.permissions_administrador', login_url='login')(  EstadoCreate.as_view()), name='estado-add'),
                       url(r'estado/list/$',permission_required('users.permissions_administrador', login_url='login')(  EstadoList.as_view()), name='list-estado'),

                       url(r'municipio/add/$',permission_required('users.permissions_administrador', login_url='login')(MunicipioCreate.as_view()), name='municipio-add'),
                       url(r'municipio/list/$',permission_required('users.permissions_administrador', login_url='login')(MunicipioList.as_view()), name='list-municipio'),

                       url(r'aula/add/$',permission_required('users.permissions_administrador', login_url='login')(  AulaCreate.as_view()), name='aula-add'),
                       url(r'aula/list/$',permission_required('users.permissions_administrador', login_url='login')(  AulaList.as_view()), name='list-aula'),

                       url(r'servicio/add/$', ServicioSocialCreate.as_view(), name='servicio-add'),
                       url(r'servicio/list/$', ServicioSocialList.as_view(), name='list-servicio'),
                       url(r'serviciolib/list/$', ServicioLiberadosList.as_view(), name='list-servicioliberados'),

users/urls.py
from django.conf.urls import patterns, include, url
from .views import UserDetailView

urlpatterns = patterns(
    '',
    url(r'log-out/$', 'users.views.LogOut', name='logout'),
    url(r'usuario/$', UserDetailView.as_view(), name='user_detail'),
    )

templates/academica/componentes/control-sidebar.html
{% load static from staticfiles %}
<aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
            <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
            <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <!-- Home tab content -->
            <div class="tab-pane active" id="control-sidebar-home-tab">
                <h3 class="control-sidebar-heading">Recent Activity</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="javascript::;">
                            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                            <div class="menu-info">
                                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                                <p>Will be 23 on April 24th</p>
                            </div>
                        </a>
                    </li>
                </ul>
                <!-- /.control-sidebar-menu -->

                <h3 class="control-sidebar-heading">Tasks Progress</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="javascript::;">
                            <h4 class="control-sidebar-subheading">
                                Custom Template Design
                                <span class="label label-danger pull-right">70%</span>
                            </h4>

                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                            </div>
                        </a>
                    </li>
                </ul>
                <!-- /.control-sidebar-menu -->

            </div>
            <!-- /.tab-pane -->
            <!-- Stats tab content -->
            <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
            <!-- /.tab-pane -->
            <!-- Settings tab content -->
            <div class="tab-pane" id="control-sidebar-settings-tab">
                <form method="post">
                    <h3 class="control-sidebar-heading">General Settings</h3>

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            Report panel usage
                            <input type="checkbox" class="pull-right" checked>
                        </label>

                        <p>
                            Some information about this general settings option
                        </p>
                    </div>
                    <!-- /.form-group -->
                </form>
            </div>
            <!-- /.tab-pane -->
        </div>
    </aside>

templates/academica/componentes/main-footer.html
{% load static from staticfiles %}
<footer class="main-footer">
        <!-- To the right -->

        <!-- Default to the left -->
        <strong>Copyright &copy; 2015 <a target="_blank" href="http://www.unisierra.edu.mx/">Siie</a>.</strong>
    </footer>

templates/academica/componentes/main-header.html
{% load static from staticfiles %}
<header class="main-header">

        <!-- Logo -->
        <a href="/Index" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>SI</b>IE</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>SI</b>IE</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Messages: style can be found in dropdown.less
                    <li class="dropdown messages-menu">
                        <!-- Menu toggle button
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-envelope-o"></i>
                            <span class="label label-success">4</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have 4 messages</li>
                            <li>
                                <!-- inner menu: contains the messages
                                <ul class="menu">
                                    <li><!-- start message
                                        <a href="#">
                                            <div class="pull-left">
                                                <!-- User Image
                                                <img  class="img-circle"
                                                    alt="User Image" src={{ user.avatar.url }}>
                                            </div>
                                            <!-- Message title and timestamp
                                            <h4>
                                                Support Team
                                                <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                            </h4>
                                            <!-- The message
                                            <p>Why not buy a new awesome theme?</p>
                                        </a>
                                    </li>
                                    <!-- end message -
                                </ul>
                                <!-- /.menu -
                            </li>
                            <li class="footer"><a href="#">See All Messages</a></li>
                        </ul>
                    </li>
                    <!-- /.messages-menu -->

                    <!-- Notifications Menu
                    <li class="dropdown notifications-menu">
                        <!-- Menu toggle button -
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">10</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have 10 notifications</li>
                            <li>
                                <!-- Inner Menu: contains the notifications --
                                <ul class="menu">
                                    <li><!-- start notification --
                                        <a href="#">
                                            <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                        </a>
                                    </li>
                                    <!-- end notification --
                                </ul>
                            </li>
                            <li class="footer"><a href="#">View all</a></li>
                        </ul>
                    </li>
                    <!-- Tasks Menu --
                    <li class="dropdown tasks-menu">
                        <!-- Menu Toggle Button --
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-flag-o"></i>
                            <span class="label label-danger">9</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have 9 tasks</li>
                            <li>
                                <!-- Inner menu: contains the tasks --
                                <ul class="menu">
                                    <li><!-- Task item --
                                        <a href="#">
                                            <!-- Task title and progress text --
                                            <h3>
                                                Design some buttons
                                                <small class="pull-right">20%</small>
                                            </h3>
                                            <!-- The progress bar --
                                            <div class="progress xs">
                                                <!-- Change the css width attribute to simulate progress --
                                                <div class="progress-bar progress-bar-aqua" style="width: 20%"
                                                     role="progressbar" aria-valuenow="20" aria-valuemin="0"
                                                     aria-valuemax="100">
                                                    <span class="sr-only">20% Complete</span>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <!-- end task item --
                                </ul>
                            </li>
                            <li class="footer">
                                <a href="#">View all tasks</a>
                            </li>
                        </ul>
                    </li>
                    <!-- User Account Menu -->
                    <li class="dropdown user user-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!-- The user image in the navbar-->
                            <img  class="user-image" alt="User Image" src={{ user.avatar.url }}>
                            <!-- hidden-xs hides the username on small devices so only the image appears. -->
                            <span class="hidden-xs">{{ user.get_full_name }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- The user image in the menu -->
                            <li class="user-header">
                                <img class="img-circle" alt="User Image" src={{ user.avatar.url }} >

                                <p>
                                    {{ user.get_full_name }}
                                    <small>{{user.groups.all.0}}</small>
                                </p>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'users:user_detail' %}" class="btn btn-default btn-flat">Perfil</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'users:logout'  %}" class="btn btn-default btn-flat">Salir</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->

                </ul>
            </div>
        </nav>
    {% if messages %}
        <div id="messages">
            {% for message in messages %}
                {% if message.message != 'Has cerrado sesión.' and 'Ha iniciado sesión' not in message.message %}
                    <div class="alert alert-block alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}">
                        <a class="close" data-dismiss="alert">×</a>
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
    </header>
    <!-- Left side column. contains the logo and sidebar -->

templates/academica/componentes/search_form.html
<form method="get" action="">
    <input type="text" name="q" value="{{ q }}" />
    <input type="submit" value="Search" />
</form>