Siie/urls.py
from . import views
# from dajaxice.core.Dajaxice import dajaxice_autodiscover
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#
# dajaxice_autodiscover()


urlpatterns = patterns('',
                       # Examples:

                       url(r'^academica/', include('academica.urls')),
                       # url(r'^/accounts/login/$', include('allauth.urls', namespace='allauth', app_name='allauth')),
                       url(r'^$', 'Siie.views.login', name="login"),
                       url(r'^Index', login_required(views.Index.as_view()), name="Index"),
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^accounts/', include('allauth.urls')),
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^markdown/', include("django_markdown.urls")),
                       url(r'^', include('users.urls', namespace='users')),
                       url(r'^', include('reportes.urls', namespace='reportes')),
                       #url(r'^%s/' % settings.DAJAXICE_MEDIA_PREFIX, include('dajaxice.urls'))

                       )

if getattr(settings, "DEBUG", False):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reportes/urls.py
from django.conf.urls import patterns, include, url
from wkhtmltopdf.views import PDFTemplateView
from reportes.views import Boleta_Semestral_To_PDF, Calificacion_por_Materia_to_PDF, Inscripcion_To_PDF,CriteriosView, \
    Reinscripcion_To_PDF, CertificadoFinal_To_PDF, Kardex_To_PDF

urlpatterns = patterns('',
                       url(r'^pdf/(?P<model>\w+)/$', CriteriosView.as_view(), name='evafinal'),
                       url(r'^report/repevafinal/$', Calificacion_por_Materia_to_PDF.as_view(), name='reporte-evafinal'),
                       url(r'^report/repboleta/$', Boleta_Semestral_To_PDF.as_view()),
                        url(r'^report/repinscrip/(?P<pk>[0-9]+)/$', Inscripcion_To_PDF.as_view()),
                       url(r'^report/reinscriprep/(?P<pk>[0-9]+)/$', Reinscripcion_To_PDF.as_view()),
                        url(r'^report/certifinalrep/(?P<pk>[0-9]+)/$', CertificadoFinal_To_PDF.as_view()),
                       url(r'^report/kardex/(?P<pk>[0-9]+)/$', Kardex_To_PDF.as_view()),
                       )

academica/models.py
# -*- encoding: utf-8 -*-
from django.core.urlresolvers import reverse

from django.db import models


class Aceptados(models.Model):
    alumno_previo = models.ForeignKey('AlumnoPrevio', blank=True, null=True)
    aceptado = models.SmallIntegerField(blank=True, null=True)
    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)


class AlumnoCalificacion(models.Model):
    # alumno = models.ForeignKey('Alumnos')
    horario = models.ForeignKey('Horario', blank=True, null=True)
    calificacion = models.IntegerField(blank=True, null=True)
    calificacion_letra = models.CharField(max_length=100, blank=True)
    semestre = models.ForeignKey('CicloSemestral')
    # materia = models.ForeignKey('Materias')
    revalidacion = models.SmallIntegerField(blank=True, null=True)
    ciclo = models.CharField(max_length=50, blank=True)

    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["calificacion"]

    def get_absolute_url(self):
        return reverse('list-evaluacion')

    def __str__(self):
        return self.calificacion_letra


class Carreras(models.Model):
    nom_carrera = models.CharField(max_length=50, blank=True)
    clave = models.CharField(max_length=50, blank=True,unique=True)
    abreviatura = models.CharField(max_length=50, blank=True)
    plan_estudio = models.ForeignKey('PlanEstudio', blank=True, null=True)
    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["nom_carrera"]

    def get_absolute_url(self):
        return reverse('list-carrera')

    def __str__(self):
        return self.nom_carrera


class Materias(models.Model):
    nom_materia = models.CharField(max_length=50, blank=True)
    clave = models.CharField(max_length=50, blank=True, unique=True)
    seriacion = models.CharField(max_length=50, blank=True, verbose_name='Serialización')
    creditos = models.IntegerField(blank=True, null=True)
    # carrera = models.ForeignKey("Carreras")
    semestre=models.ForeignKey('Semestre',to_field='clave',null=True,blank=True)
    profesor=models.ForeignKey('Maestros',to_field='no_expediente',null=True,blank=True)
    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["nom_materia"]

    def get_absolute_url(self):
        return reverse('list-materias')

    def __str__(self):
        return self.nom_materia


class AlumnoPrevio(models.Model):
    alumno = models.ForeignKey("Alumnos", unique=True)

    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.alumno.nom_alumno + " " + self.alumno.apellido_paterno + " " + self.alumno.apellido_materno


class AlumnoProyecto(models.Model):
    alumno = models.ForeignKey('Alumnos', blank=True, null=True)
    proyecto = models.ForeignKey('ServicioEstadia', blank=True, null=True)
    concluyo = models.SmallIntegerField(blank=True, null=True)
    calificado = models.SmallIntegerField(blank=True, null=True)

    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)


class Alumnos(models.Model):
    nom_alumno = models.CharField(max_length=200, verbose_name='Nombre', db_index=True)
    apellido_materno = models.CharField(max_length=50)
    apellido_paterno = models.CharField(max_length=50)
    curp = models.CharField(max_length=25, blank=True)
    edad = models.IntegerField(blank=True, null=True, )
    sexo = models.CharField(max_length=10, blank=True, verbose_name='genero')
    edo_civil = models.CharField(max_length=50, blank=True, verbose_name='Estado Civil')
    tipo_sangre = models.CharField(max_length=10, blank=True)
    servicio_medico = models.SmallIntegerField(blank=True, null=True)
    instituto = models.CharField(max_length=50, blank=True)
    num_afiliacion = models.CharField(max_length=50, blank=True, verbose_name='No De Afiliación')
    generacion = models.IntegerField(blank=True, null=True)
    tipo = models.CharField(max_length=50, blank=True)
    plan = models.ForeignKey('PlanEstudio',to_field='clave_plan',blank=True,null=True)
    no_expediente = models.CharField(max_length=50,blank=True)
    matricula = models.CharField(max_length=20, blank=False, null=False,unique=True)
    semestre = models.ForeignKey('CicloSemestral',to_field='clave', blank=True,null=True)
    condicionado = models.SmallIntegerField(blank=True, null=True,verbose_name='Status')
    domicilio = models.CharField(max_length=100, blank=True)
    colonia = models.CharField(max_length=50, blank=True)
    localidad = models.CharField(max_length=50, blank=True)
    municipio = models.CharField(max_length=50,blank=True,null=True)
    cp = models.CharField(max_length=50, blank=True, verbose_name='Codigo Postal')
    telefono = models.CharField(max_length=50, blank=True)
    lugar_nac = models.CharField(max_length=50, blank=True, null=True, verbose_name='Lugar de nacimiento')
    fecha_nacimiento = models.DateField(blank=True, null=True)
    alergias = models.CharField(max_length=50, blank=True)
    enfermedades = models.CharField(max_length=50, blank=True, verbose_name='Padecimientos')
    contacto_emergencia = models.CharField(max_length=50, blank=True)
    contacto_domicilio = models.CharField(max_length=100, blank=True)
    contacto_tel = models.CharField(max_length=50, blank=True)
    nombre_tutor = models.CharField(max_length=50, blank=True)
    nombre_materno = models.CharField(max_length=50, blank=True)
    domicilio_tutor = models.CharField(max_length=100, blank=True)
    localidad_tutor = models.CharField(max_length=50, blank=True)
    telefono_tutor = models.CharField(max_length=50, blank=True)
    ocupacion_tutor = models.CharField(max_length=50, blank=True)
    sueldo_mensual = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    domicilio_madre = models.CharField(max_length=100, blank=True)
    localidad_madre = models.CharField(max_length=50, blank=True)
    telefono_madre = models.CharField(max_length=50, blank=True)
    trabaja_actualmente = models.BooleanField(default=False)
    puesto = models.CharField(max_length=50, blank=True)
    sueldo_mensual_alumno = models.DecimalField(max_digits=19, decimal_places=4, blank=True, null=True)
    transporte = models.SmallIntegerField(blank=True, null=True)
    transporte_universidad = models.SmallIntegerField(blank=True, null=True)
    deporte_practica = models.CharField(max_length=50, blank=True)
    musica = models.BooleanField(default=False)
    teatro = models.BooleanField(default=False)
    declamacion = models.BooleanField(default=False)
    oratoria = models.BooleanField(default=False)
    otro_interes = models.BooleanField(default=False,verbose_name='otros')
    credencial = models.SmallIntegerField(blank=True, null=True)
    foto = models.ImageField(upload_to='fotos',blank=True , default='foto.png')
    firma = models.ImageField(upload_to='firma',blank=True)

    escuela_procedencia = models.ForeignKey('Escuela',blank=True, null=True, verbose_name='Escuela')
    anio_egreso=models.CharField(max_length=5,blank=True, null=True,verbose_name='Egreso')
    promedio_bachiller=models.IntegerField(verbose_name='Promedio', null=True, blank=True)

    password = models.CharField(max_length=50, blank=True)
    email = models.EmailField(unique=True)
    extracurriculares = models.ManyToManyField('Extracurriculares', blank=True, null=True)
    is_deuda = models.BooleanField(default=False)

    carrera = models.ForeignKey("Carreras",to_field='clave',blank=True, null=True)
    # nuevos campos
    grupo = models.ForeignKey('Grupos',to_field='clave',blank=True, null=True)

    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["nom_alumno"]
        permissions = (
            ("can_view_servicios_escolares", "Servicios Escolares"),
        )

    def get_absolute_url(self):
        return reverse('list-alumno')

    def __str__(self):
        return self.nom_alumno + " " + self.apellido_paterno + " " + self.apellido_materno


class Extracurriculares(models.Model):
    nom_materia = models.CharField(max_length=50, blank=True,null=True)
    clave = models.CharField(max_length=50, blank=True,null=True, unique=True)
    tipo = models.CharField(max_length=50, blank=True,null=True)
    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.nom_materia

    def get_absolute_url(self):
        return reverse('list-extra')


class AlumnosAsesorados(models.Model):
    nombre = models.CharField(max_length=50, blank=True)
    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)


class Aulas(models.Model):
    nom_aula = models.CharField(max_length=50, blank=True)
    edificio = models.CharField(max_length=50, blank=True)

    alta_date_created = models.DateTimeField(auto_now_add=True)
    baja_date_created = models.DateTimeField(blank=True, null=True)

reportes/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset
from academica.models import Alumnos

__author__ = 'Luisk'
from django import forms


class InscripcionReporteForm(forms.ModelForm):
    helper = FormHelper()
    helper.add_input(Submit('submit', 'Guardar'))
    helper.layout = Layout(Fieldset(
        'Datos Personales',
        'is_active',
        'nom_alumno',
        'apellido_paterno',
        'apellido_materno',
        )
    )

    class Meta:
        model = Alumnos
        fields = '__all__'

reportes/views.py
from django.utils import timezone
import datetime
import json
from django.http.response import HttpResponse
from django.shortcuts import render_to_response, redirect
from django.template.context import RequestContext
from django.views.generic.base import View, TemplateView
from django.views.generic.detail import DetailView
from wkhtmltopdf.views import PDFTemplateResponse
from academica.models import Alumnos, Grupos, Calificaciones, Materias, PlanEstudio, Carreras, CicloSemestral
from reportes.forms import InscripcionReporteForm


class CriteriosView(TemplateView):

    def get_context_data(self, **kwargs):
        cxt = super(CriteriosView, self).get_context_data(**kwargs)
        cxt = {'carreras': Carreras.objects.all(), 'materias': Materias.objects.all(), 'grupos': Grupos.objects.all(),
               'semestres': CicloSemestral.objects.all(),'alumnos':Alumnos.objects.all()}
        print('id' + self.kwargs['model'])
        return cxt

    def get_template_names(self):
        model = self.kwargs['model']
        self.model = model
        if model == "boleta":
            self.template_name = "reportes/%s_form.html" % model
        if model == "evafinal":
            self.template_name = "reportes/%s_form.html" % model
        if model=='inscripcion':
            self.template_name="reportes/%s_form.html" % model
        if model=='reinscripcion':
            self.template_name="reportes/%s_form.html" % model
        if model=='certifinal':
            self.template_name="reportes/%s_form.html" % model
        if model=='kardex':
            self.template_name="reportes/%s_form.html" % model

        return self.template_name


class Calificacion_por_Materia_to_PDF(TemplateView):
    template_name = 'reportes/reporte_evafinal_form.html'

    # def datos_evafinal_ajax(request):
    #     if request.is_ajax():
    #
    #         print(request.GET['carrera'])
    #         print(request.GET['materia'])
    #         print(request.GET['ciclo'])
    #         print(request.GET['grupo'])
    #         print(request.GET['semestre'])
    #         retorno=()
    #
    #         return HttpResponse('reportes/reporte_evafinal_form.html',json.dumps(retorno))
    #     else:
    #         return redirect('/')



class Boleta_Semestral_To_PDF(TemplateView):
    template_name = 'reportes/reporte_boleta_form.html'


class Inscripcion_To_PDF(DetailView):
    template_name = 'reportes/reporte_inscripcion.html'
    form_class = InscripcionReporteForm
    model = Alumnos

    def get_context_data(self, **kwargs):
        cxt = super(Inscripcion_To_PDF, self).get_context_data(**kwargs)
        hoy = datetime.datetime.now()
        hoy = hoy.strftime('%Y-%m-%d')
        alumno=Alumnos.objects.get(id=self.kwargs['pk'])
        fecha_ins=alumno.alta_date_created.strftime('%Y-%m-%d')
        cxt = {'hoy': hoy,'fecha_insc':fecha_ins,'object':alumno}

        return cxt

class Reinscripcion_To_PDF(DetailView):
    template_name = 'reportes/reporte_reinscripcion.html'
    form_class = InscripcionReporteForm
    model = Alumnos

    def get_context_data(self, **kwargs):
        cxt = super(Reinscripcion_To_PDF, self).get_context_data(**kwargs)
        hoy = datetime.datetime.now()
        hoy = hoy.strftime('%Y-%m-%d')
        alumno=Alumnos.objects.get(id=self.kwargs['pk'])
        fecha_ins=alumno.alta_date_created.strftime('%Y-%m-%d')
        cxt = {'hoy': hoy,'fecha_insc':fecha_ins,'object':alumno}

        return cxt

class CertificadoFinal_To_PDF(TemplateView):
    template_name = 'reportes/reporte_certificado_final.html'
    #
    def get_context_data(self, **kwargs):
        cxt = super(CertificadoFinal_To_PDF, self).get_context_data(**kwargs)
        hoy = datetime.datetime.now()
        hoy = hoy.strftime('%Y-%m-%d')
        alumno=Alumnos.objects.get(id=self.kwargs['pk'])
        calificaciones=Calificaciones.objects.filter(matricula=alumno.matricula)

        cxt = {'hoy': hoy,'var':'hola mundo','object':alumno,'calificaciones':calificaciones}

        return cxt

class Kardex_To_PDF(TemplateView):
    template_name = 'reportes/reporte_kardex.html'

    #
    def get_context_data(self, **kwargs):
        cxt = super(Kardex_To_PDF, self).get_context_data(**kwargs)
        hoy = datetime.datetime.now()
        anio=hoy.year
        hoy = hoy.strftime('%Y-%m-%d')
        alumno=Alumnos.objects.get(id=self.kwargs['pk'])
        calificaciones=Calificaciones.objects.filter(matricula=alumno.matricula)

        cxt = {'hoy': hoy,'var':'hola mundo','object':alumno,'calificaciones':calificaciones,'anio':anio}

        return cxt

templates/reportes/Reporte_Calificacion_Final.html
{% extends 'reportes/base_reporte.html' %}
{% load static from staticfiles %}

{% block codigo %}
<b>Codigo:</b>10-01-023
{% endblock %}
        {% block report_name  %}
Acta de Evaluacion final
    {% endblock %}
{% block content_report %}
 <br>
      <br>
          <!-- info row -->
          <div class="row invoice-info">
            <div class="col-sm-12 invoice-col">
              <address>
                <strong>Programa Educativo: </strong>
                {{ plan }}<br>

              </address>
            </div><!-- /.col -->
            <div class="col-sm-12 invoice-col">
               <address>
                <strong>Asignatura: </strong>
                {{ materia }}<br>
                </address>
            </div><!-- /.col -->
            <div class="col-sm-4 invoice-col">
              <b>Ciclo Escolar: </b><br>{{ ciclo }}
            </div><!-- /.col -->
              <div class="col-sm-4 invoice-col">
              <b>Semestre: </b>
                  <br>{{ semestre }}
            </div><!-- /.col -->
              <div class="col-sm-4 invoice-col">
              <b>Grupo: </b><br>{{ grupo }}
            </div><!-- /.col -->

          </div><!-- /.row -->
<br>
      <br>
          <!-- Table row -->
          <div class="row">
            <div class="col-xs-12 table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>No.Expediente</th>
                    <th>Nombre del Alumno</th>
                    <th>Numero</th>
                    <th>Letra</th>

                  </tr>
                </thead>
                <tbody>
                {% if listado %}
                {% for c in listado %}
                  <tr>
                    <td>{{ c.matricula }}</td>
                    <td>{{ c.matricula.nombre }}</td>
                    <td>{{ c.final }}</td>
                    <td>El snort testosterone trophy driving gloves handsome</td>

                  </tr>
                {% endfor %}
                    {% else %}
                    <tr>
                    <td>No existen calificaciones con estos datos</td>
                    </tr>

                {% endif %}

                </tbody>
              </table>
            </div><!-- /.col -->
          </div><!-- /.row -->


{% endblock %}

{% block data_footer %}
    <br>
      <br>
          <div class="row">
            <!-- -->
            <div class="col-xs-6">
              <b class="lead">Profesor de la asignatura :</b>
                <br>El Profe Rodriguez

            </div><!-- /.col -->
            <div class="col-xs-6">
              <b class="lead">Jefe de la división de:{{ grupo.carrera }}</b><br>
            Perico Perez Ripiao
            </div><!-- /.col -->
          </div><!-- /.row -->
      <br>
      <br>

     <div class="pull-left">
              <small>Calificacion Minima Aprobatoria: 70.<br>
Nota: En caso de tachaduras o enmendaduras al formato, no tendrá validez oficial.</small>
<br>
     </div>
{% endblock %}

templates/reportes/Reporte_boleta_semestral.html
{% extends 'reportes/base_reporte.html' %}
{% block codigo %}
<b>Codigo:</b>10-01-023
{% endblock %}
{% block report_name  %}
Boleta de Evaluacion Semestral
    {% endblock %}

{% block content_report %}
 <br>
      <br>
          <!-- info row -->
          <div class="row invoice-info">
            <div class="col-sm-12 invoice-col">
              <address>
                <strong>Nombre: </strong>
                {{ alumno }}<br>

              </address>
            </div><!-- /.col -->
            <div class="col-sm-12 invoice-col">
               <address>
                <strong>Matricula: </strong>
                {{ alumno.matricula }}<br>
                </address>
            </div><!-- /.col -->
            <div class="col-sm-4 invoice-col">
              <b>Plan de Estudios: </b><br>{{ alumno.plan }}
            </div><!-- /.col -->
              <div class="col-sm-4 invoice-col">
              <b>Semestre: </b>
                  <br>{{ alumno.semestre }}
            </div><!-- /.col -->
              <div class="col-sm-4 invoice-col">
              <b>Grupo: </b><br>
            </div><!-- /.col -->

          </div><!-- /.row -->
<br>
      <br>
          <!-- Table row -->
          <div class="row">
            <div class="col-xs-12 table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Clave de Asignatura</th>
                    <th>Nombre de la Asignatura</th>
                    <th>Numero</th>
                    <th>Letra</th>

                  </tr>
                </thead>
                <tbody>
                {% if listado %}
                {% for c in listado %}
                  <tr>
                    <td>{{ c.materia.clave }}</td>
                    <td>{{ c.materia.nom_materia }}</td>
                    <td>{{ c.final }}</td>
                    <td>handsome</td>

                  </tr>
                {% endfor %}
                     {% else %}
                    <tr>
                    <td>No existen calificaciones para este estudiante</td>
                    </tr>

                {% endif %}

                </tbody>
              </table>
            </div><!-- /.col -->
          <div class="pull-right">
         <b>PROMEDIO GENERAL:<small>NOTA</small></b>
      </div>
          </div><!-- /.row -->

{% endblock %}

{% block data_footer %}
     <div class="col-xs-12">
              <b>C.p. Omar Armenta Gonzalez<br>
EL JEFE DEL DEPARTAMENTO DE SERVICIOS ESCOLARES</b>
            </div><!-- /.col -->
         <div class="col-xs-12">
              <small> Nota: El presente documento tiene un carácter meramente informativo sobre el estado académico del alumno.</small>
            </div><!-- /.col -->

{% endblock %}

templates/reportes/reporte_evafinal_form.html
{% extends 'reportes/base_reporte.html' %}
{% load static from staticfiles %}
{% block content %}
            <form id="myForm" method="post" action="">

  <section class="invoice">
          <!-- title row -->
          <div class="row">
                <div class="col-xs-12">
                     <span class="logo-lg pull-left"><img class="img-responsive" src="{% static 'images/logosiie.png' %}" alt="logo">   </span>
                    <h2 class="page-header"><b>
                       Universidad de la Sierra
                        </b>
                        <small class="pull-right">
                            <b>Código:</b>10-01-023
                        </small>
                    </h2>
                </div>
                <!-- /.col -->
            </div>
        <div class="row">
            <div class="col-xs-12">
              <h1 class="pull-right">
            Acta de Evaluación final
 </h1>
            </div><!-- /.col -->
          </div>
      <br>
      <br>
          <!-- info row -->
          <div class="row invoice-info">
            <div class="col-sm-12 invoice-col">
              <address>
                <strong>Programa Educativo: </strong>
                  <small id="id_programa"></small>
                <br>

              </address>
            </div><!-- /.col -->
            <div class="col-sm-12 invoice-col">
               <address>
                <strong>Asignatura: </strong>
                <small id="id_materia"></small><br>
                </address>
            </div><!-- /.col -->
            <div class="col-sm-4 invoice-col">
              <b>Ciclo Escolar: </b><br><small id="id_ciclo"></small>
            </div><!-- /.col -->
              <div class="col-sm-4 invoice-col">
              <b>Semestre: </b>
                  <br><small id="id_semestre"></small>
            </div><!-- /.col -->
              <div class="col-sm-4 invoice-col">
              <b>Grupo: </b><br><small id="id_grupo"></small>
            </div><!-- /.col -->

          </div><!-- /.row -->
<br>
      <br>
          <!-- Table row -->
          <div class="row">
            <div class="col-xs-12 table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>No.Expediente</th>
                    <th>Nombre del Alumno</th>
                    <th>Numero</th>
                    <th>Letra</th>

                  </tr>
                </thead>
                <tbody id="result_table_body">

                    <tr>
                    <td>No existen calificaciones con estos datos</td>
                    </tr>
                </tbody>
              </table>
            </div><!-- /.col -->
          </div><!-- /.row -->
<small class="pull-right">Moctezuma,Sonora,Mexico ,a 2/10/2014</small>
    <br>
      <br>
          <div class="row">
            <!-- -->
            <div class="col-xs-6">
              <b class="lead">Profesor:</b>
                <br>El Profe Rodriguez

            </div><!-- /.col -->
            <div class="col-xs-6">
              <b class="lead">Jefe de la división de:{{ grupo.carrera }}</b><br>
            Perico Perez Ripiao
            </div><!-- /.col -->
          </div><!-- /.row -->
      <br>
      <br>

     <div class="pull-left">
              <small>Calificacion Minima Aprobatoria: 70.<br>
Nota: En caso de tachaduras o enmendaduras al formato, no tendrá validez oficial.</small>
<br>
     </div>
 <div class="pull-right">
         <img class="profile-user-img img-responsive img-circle" src="{% static 'images/sello1.png' %}" alt="Sello del documento">
      </div>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
 <br>
      <br>
      <br>
      <br>
      <br>
      <br>
          <!-- this row will not appear when printing -->
          <div class="row no-print">
            <div class="col-xs-12">
              <a href="#" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>
              <button class="btn btn-success pull-right"><i class="fa fa-remove"></i> Cancelar</button>
              <button class="btn btn-primary pull-right" style="margin-right: 5px;"><i class="fa fa-download"></i> Generar PDF</button>
            </div>
          </div>
        </section>
</form>
{% endblock %}